config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :cards do
    collection do
      get 'card_urls'
    end
  end
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :get_card, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, only: [:new, :edit]

  def index
    @cards = params[:category_id] ? Card.where(category_id: params[:category_id]) : Card.all
  end

  def show
    @category = @card.category
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "#{@card.name}",
            :layout =>'pdf.html.erb',
            :template => 'cards/pdf.html.erb',
            :page_size => "A4",
            :disposition => 'attachment'
      end
    end
  end

  def new
    @card = Card.new
  end

  def create
    card = Card.new(card_params)
    if card.save!
      flash[:notice] = "Your new Montessori Card is here!"
      redirect_to card_path(card)
    else
      flash[:error] = "Ups. Something went wrong.."
      render :new
    end
  end

  def update
    if @card.update(card_params)
      flash[:notice] = "Your Montessori Card has been updated."
      redirect_to card_path(@card)
    else
      flash[:error] = "Ups. Something went wrong.."
      render :edit
    end
  end

  def destroy
    if @card.destroy
      flash[:notice] = "Your Montessori Card has been deleted."
      redirect_to cards_path
    else
      flash[:error] = "Ups. Something went wrong.."
      render :show
    end
  end

  def card_urls
    begin
      card_urls = WikimediaConnector.new(params[:card_name]).get_urls
      render json: { urls: card_urls }
    rescue Wikimedia::Error
      render json: { error: "No image found" }, status: :unprocessable
    end
  end

  private

  def get_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :category_id, :url)
  end

  def get_categories
    @categories = Category.all.map { |category| [category.name, category.id]}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :get_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @cards = @category.cards
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    if category.save!
      flash[:notice] = "Your new Montessori Set is here! Add some cards."
      redirect_to category_path(category)
    else
      flash[:error] = "Ups. Something went wrong.."
      render :new
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Your Montessori Set has been updated."
      redirect_to category_path(@category)
    else
      flash[:error] = "Ups. Something went wrong.."
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "Your Montessori Set has been deleted."
      redirect_to categories_path
    else
      flash[:error] = "Ups. Something went wrong.."
      render :show
    end
  end

  private

  def get_category
    @category = Category.includes(:cards).find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="small-12 large-7 columns">
  <div class='card-image-container'>
    <%= image_tag @card.url, class: "card-image-tag"%>
  </div>
  <div class='card-name-container'>
    <%= @card.name %>
  </div>
</div>

app/views/cards/_cards.html.erb
<div class="row">
  <% if @cards %>
    <% @cards.each do |card| %>
      <div class="small-12 medium-6 large-3 columns">
        <%= link_to(card) do %>
          <div class='card-image-container thumb'>
            <%= image_tag card.url %>
          </div>
          <div class='card-name-container thumb'>
            <%= card.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="small-12 columns">
      <h3>You don't have any cards yet. <%= link_to "Create your first card", new_card_path %>.</h3>
    </div>
  <% end %>
</div>

app/views/cards/_form.html.erb
<div class="row">
  <div class="small-12 medium-4 column">
    Name: <%= f.text_field :name, id: "card-name" %>
    Set: <%= f.select :category_id, @categories %>
    <%= f.hidden_field :url, id: "card-url" %>
    <%= f.submit "Save changes", class:"button expanded" %>
  </div>

  <div class="small-2 medium-1 column button-container">
    <%= button_tag "<", type:"button arrow-button", id:"btn-previous" %>
  </div>

  <div class="small-8 medium-6 column">
    <div class='card-image-container'>
      <%= image_tag @card.url, class:"card-image-tag" %>
    </div>
  </div>

  <div class="small-2 medium-1 column button-container">
    <%= button_tag ">", type:"button arrow-button", id:"btn-next" %>
  </div>
</div>

app/views/cards/edit.html.erb
<div class="row">
  <div class="small-12 column">
  	<h1>Edit this card</h1>
  </div>
</div>
<br>
<div class="row">
  <div class="small-12 column">
    <%= form_for(@card) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/cards/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Cards</h1>
  </div>
</div>
<%= render 'cards' %>

app/views/cards/new.html.erb
<h1>Cards#new</h1>
<p>Find me in app/views/cards/new.html.erb</p>

app/views/cards/pdf.html.erb
<div class="pdf-container">
  <div class='pdf-card-image-container' style="background-image: url(<%= @card.url %>)">
  </div>
  <div class='pdf-card-name-container'>
    <%= @card.name %>
  </div>
</div>

<div style='page-break-after:always;'></div>

<div class="pdf-container">
  <div class='pdf-card-image-container not-separate-image' style="background-image: url(<%= @card.url %>)">
  </div>
  <div class='pdf-card-name-container not-separate-name'>
    <%= @card.name %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="row">
  <div class="small-12 large-5 columns">
    <h6><%= link_to "<< Back to all cards", category_path(@category) %></h6>
  </div>
</div>
<div class="row">
  <div class="small-12 large-5 columns">
    <h2><%= @category.name %></h2>
    <h3><%= @card.name %></h3>
    <div>
      <%= link_to "Download PDF", :action => "show", :format => :pdf, data: {turbolinks: false} %>
    </div>
    <div>
      <%= link_to "Edit card", :action => "edit" %>
    </div>
  </div>
  
  <%= render 'card' %>
</div>

app/views/categories/_form.html.erb
<%= f.label :name, value:"Set name:", class:"label" %>
<%= f.text_field :name, class:"input" %>
<%= f.submit "Save changes", class:"button expanded" %>

app/views/categories/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Card sets</h1>
  </div>
</div>

<div class="row">
  <% if @categories.any? %>
    <% @categories.each do |category| %>
      <div class="small-12 medium-6 large-3 columns">
        <%= link_to(category) do %>
          <div class='card-image-container not-separate-image thumb'>
            <%= image_tag category.cards.first.url %>
          </div>
          <div class='card-name-container not-separate-name thumb'>
            <%= category.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="small-12 columns">
      <h3>You don't have any cards sets yet. <%= link_to "Create your first set", new_category_path %>.</h3>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="row">
  <div class="small-12 column">
  	<h1>Create new set</h1>
  </div>
</div>
<br>
<div class="row">
  <div class="small-12 column">
    <%= form_for(@category) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h6><%= link_to "<< Back to all sets", categories_path %></h6>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h1><%= @category.name %></h1>
  </div>
</div>
<%= render 'cards/cards' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Montessori Card</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>